# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XJzxdqp1od8jkDk710sAKXTfvoDDTAUQ
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

data=pd.read_csv('/content/drive/MyDrive/publicdrive/knn.txt',header=None,delim_whitespace=True)
print(data)

X=data[[0,1,2,3,4]].to_numpy()
Y=data[[5]].to_numpy()

## knn = KNeighborsClassifier(n_neighbors)
knn = KNeighborsClassifier(n_neighbors=5,p=2)
knn.fit(X,Y)
##print('Accuracy of K-NN classifier on training set: {:.2f}'.format(knn.score(X,Y)))
knn.score(X, Y, sample_weight=None)

pred = knn.predict(X)
print(confusion_matrix(Y, pred))
print(classification_report(Y, pred))